name: booky
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_speed_dial: ^7.0.0
  protobuf: 3.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  grpc: ^3.2.4
  shared_preferences: ^2.2.3 
  get_it: ^7.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  injectable: ^2.4.2
  flutter_svg_icons: ^0.0.1+4
  easy_debounce: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  protoc_plugin:
  injectable_generator: ^2.6.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/

